import type {
  ProductTemplate,
  FontOption,
  ClipartCategory,
  ClipartItem,
  ProductColor,
  DesignTemplate,
  DesignTemplateCategory,
} from "@/types/designer";

/* ─── Default Product Colors ─── */
export const defaultProductColors: ProductColor[] = [
  { name: "White", hex: "#FFFFFF" },
  { name: "Black", hex: "#1A1A1A" },
  { name: "Navy", hex: "#1B2A4A" },
  { name: "Brand Green", hex: "#a7cf45" },
  { name: "Red", hex: "#DC2626" },
  { name: "Royal Blue", hex: "#1D4ED8" },
  { name: "Grey", hex: "#6B7280" },
  { name: "Sand", hex: "#D4A853" },
];

/* ─── Product Templates ─── */
export const productTemplates: ProductTemplate[] = [
  {
    id: "tshirt-classic",
    type: "t-shirt",
    name: "Classic T-Shirt",
    description: "Unisex cotton crew-neck tee — perfect for custom prints",
    colors: defaultProductColors,
    views: [
      {
        id: "front",
        label: "Front",
        printArea: { top: 12, left: 15, width: 70, height: 60 },
        mockupImage: "/images/products/tshirt-front.png",
      },
      {
        id: "back",
        label: "Back",
        printArea: { top: 10, left: 15, width: 70, height: 65 },
        mockupImage: "/images/products/tshirt-back.png",
      },
    ],
    basePriceInPence: 1999,
    category: "Clothing",
    thumbnail: "/images/products/tshirt-thumb.png",
  },
  {
    id: "hoodie-pullover",
    type: "hoodie",
    name: "Pullover Hoodie",
    description: "Warm cotton-blend hoodie with front pouch pocket",
    colors: defaultProductColors,
    views: [
      {
        id: "front",
        label: "Front",
        printArea: { top: 15, left: 15, width: 70, height: 55 },
        mockupImage: "/images/products/hoodie-front.png",
      },
      {
        id: "back",
        label: "Back",
        printArea: { top: 10, left: 15, width: 70, height: 60 },
        mockupImage: "/images/products/hoodie-back.png",
      },
    ],
    basePriceInPence: 3999,
    category: "Clothing",
    thumbnail: "/images/products/hoodie-thumb.png",
  },
  {
    id: "sweatshirt-crew",
    type: "sweatshirt",
    name: "Crew Sweatshirt",
    description: "Classic crew-neck sweatshirt in heavyweight cotton",
    colors: defaultProductColors,
    views: [
      {
        id: "front",
        label: "Front",
        printArea: { top: 14, left: 15, width: 70, height: 56 },
        mockupImage: "/images/products/sweatshirt-front.png",
      },
      {
        id: "back",
        label: "Back",
        printArea: { top: 10, left: 15, width: 70, height: 62 },
        mockupImage: "/images/products/sweatshirt-back.png",
      },
    ],
    basePriceInPence: 3499,
    category: "Clothing",
    thumbnail: "/images/products/sweatshirt-thumb.png",
  },
  {
    id: "tote-bag-standard",
    type: "tote-bag",
    name: "Cotton Tote Bag",
    description: "Natural cotton tote — ideal for eco-friendly branding",
    colors: [
      { name: "Natural", hex: "#F5F0E8" },
      { name: "Black", hex: "#1A1A1A" },
      { name: "Navy", hex: "#1B2A4A" },
    ],
    views: [
      {
        id: "front",
        label: "Front",
        printArea: { top: 8, left: 10, width: 80, height: 75 },
        mockupImage: "/images/products/tote-front.png",
      },
    ],
    basePriceInPence: 1499,
    category: "Accessories",
    thumbnail: "/images/products/tote-thumb.png",
  },
  {
    id: "mug-ceramic",
    type: "mug",
    name: "Ceramic Mug (11oz)",
    description: "Classic white ceramic mug — dishwasher safe",
    colors: [{ name: "White", hex: "#FFFFFF" }],
    views: [
      {
        id: "front",
        label: "Wrap",
        printArea: { top: 15, left: 10, width: 80, height: 55 },
        mockupImage: "/images/products/mug-front.png",
      },
    ],
    basePriceInPence: 1299,
    category: "Drinkware",
    thumbnail: "/images/products/mug-thumb.png",
  },
  {
    id: "cap-snapback",
    type: "cap",
    name: "Snapback Cap",
    description: "Structured snapback with embroidery-ready front panel",
    colors: defaultProductColors.slice(0, 5),
    views: [
      {
        id: "front",
        label: "Front",
        printArea: { top: 8, left: 15, width: 70, height: 48 },
        mockupImage: "/images/products/cap-front.png",
      },
    ],
    basePriceInPence: 1699,
    category: "Accessories",
    thumbnail: "/images/products/cap-thumb.png",
  },
  {
    id: "apron-chef",
    type: "apron",
    name: "Chef's Apron",
    description: "Full-length apron with adjustable neck strap",
    colors: [
      { name: "Black", hex: "#1A1A1A" },
      { name: "White", hex: "#FFFFFF" },
      { name: "Navy", hex: "#1B2A4A" },
    ],
    views: [
      {
        id: "front",
        label: "Front",
        printArea: { top: 6, left: 15, width: 70, height: 58 },
        mockupImage: "/images/products/apron-front.png",
      },
    ],
    basePriceInPence: 1899,
    category: "Clothing",
    thumbnail: "/images/products/apron-thumb.png",
  },
  {
    id: "glass-can-16oz",
    type: "glass-can",
    name: "Glass Can (16oz)",
    description: "Trendy glass can tumbler with bamboo lid",
    colors: [{ name: "Clear", hex: "#E8F4F8" }],
    views: [
      {
        id: "front",
        label: "Wrap",
        printArea: { top: 10, left: 10, width: 80, height: 65 },
        mockupImage: "/images/products/glasscan-front.png",
      },
    ],
    basePriceInPence: 1599,
    category: "Drinkware",
    thumbnail: "/images/products/glasscan-thumb.png",
  },
  {
    id: "tumbler-20oz",
    type: "tumbler",
    name: "Insulated Tumbler (20oz)",
    description: "Stainless steel tumbler — keeps drinks hot or cold",
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#1A1A1A" },
      { name: "Gold", hex: "#D4A853" },
    ],
    views: [
      {
        id: "front",
        label: "Wrap",
        printArea: { top: 8, left: 10, width: 80, height: 70 },
        mockupImage: "/images/products/tumbler-front.png",
      },
    ],
    basePriceInPence: 1899,
    category: "Drinkware",
    thumbnail: "/images/products/tumbler-thumb.png",
  },
  {
    id: "pillowcase-square",
    type: "pillowcase",
    name: "Square Pillowcase",
    description: "Soft polyester pillowcase — vibrant sublimation print",
    colors: [{ name: "White", hex: "#FFFFFF" }],
    views: [
      {
        id: "front",
        label: "Front",
        printArea: { top: 5, left: 5, width: 90, height: 90 },
        mockupImage: "/images/products/pillowcase-front.png",
      },
    ],
    basePriceInPence: 1899,
    category: "Home & Living",
    thumbnail: "/images/products/pillowcase-thumb.png",
  },
];

/* ─── Font Library ─── */
export const designerFonts: FontOption[] = [
  { family: "Inter", category: "sans-serif" },
  { family: "Playfair Display", category: "serif" },
  { family: "Roboto", category: "sans-serif" },
  { family: "Open Sans", category: "sans-serif" },
  { family: "Montserrat", category: "sans-serif" },
  { family: "Lato", category: "sans-serif" },
  { family: "Poppins", category: "sans-serif" },
  { family: "Oswald", category: "sans-serif" },
  { family: "Raleway", category: "sans-serif" },
  { family: "Merriweather", category: "serif" },
  { family: "Lora", category: "serif" },
  { family: "PT Serif", category: "serif" },
  { family: "Bebas Neue", category: "display" },
  { family: "Lobster", category: "display" },
  { family: "Permanent Marker", category: "handwriting" },
  { family: "Pacifico", category: "handwriting" },
  { family: "Dancing Script", category: "handwriting" },
  { family: "Caveat", category: "handwriting" },
  { family: "Shadows Into Light", category: "handwriting" },
  { family: "Source Code Pro", category: "monospace" },
  { family: "Abril Fatface", category: "display" },
  { family: "Righteous", category: "display" },
  { family: "Bangers", category: "display" },
  { family: "Press Start 2P", category: "display" },
  { family: "Anton", category: "sans-serif" },
  { family: "Archivo Black", category: "sans-serif" },
  { family: "Titan One", category: "display" },
  { family: "Sacramento", category: "handwriting" },
  { family: "Great Vibes", category: "handwriting" },
  { family: "Satisfy", category: "handwriting" },
];

/* ─── Clipart Categories ─── */
export const clipartCategories: ClipartCategory[] = [
  { id: "badges", name: "Badges & Frames", icon: "Shield" },
  { id: "sports", name: "Sports & Fitness", icon: "Trophy" },
  { id: "nature", name: "Nature & Outdoors", icon: "TreePine" },
  { id: "love", name: "Love & Hearts", icon: "Heart" },
  { id: "icons", name: "Icons & Symbols", icon: "Star" },
  { id: "decorative", name: "Borders & Dividers", icon: "Minus" },
  { id: "music", name: "Music & Arts", icon: "Music" },
  { id: "food", name: "Food & Kitchen", icon: "Coffee" },
  { id: "typography", name: "Text Frames", icon: "Type" },
];

/* ─── Clipart Items ─── */
export const clipartItems: ClipartItem[] = [
  /* Badges & Frames */
  {
    id: "badge-circle",
    name: "Circle Badge",
    category: "badges",
    url: "/clipart/badges/circle-badge.svg",
    tags: ["badge", "frame", "circle", "border"],
  },
  {
    id: "badge-rectangle",
    name: "Rectangle Badge",
    category: "badges",
    url: "/clipart/badges/rectangle-badge.svg",
    tags: ["badge", "frame", "rectangle", "border"],
  },
  {
    id: "badge-hexagon",
    name: "Hexagon Badge",
    category: "badges",
    url: "/clipart/badges/hexagon-badge.svg",
    tags: ["badge", "frame", "hexagon", "border"],
  },
  {
    id: "badge-star",
    name: "Star Badge",
    category: "badges",
    url: "/clipart/badges/star-badge.svg",
    tags: ["badge", "star", "frame"],
  },
  {
    id: "badge-oval",
    name: "Oval Badge",
    category: "badges",
    url: "/clipart/badges/oval-badge.svg",
    tags: ["badge", "oval", "frame", "ellipse"],
  },

  /* Sports & Fitness */
  {
    id: "sport-football",
    name: "Football",
    category: "sports",
    url: "/clipart/sports/football.svg",
    tags: ["football", "soccer", "ball", "sport"],
  },
  {
    id: "sport-trophy",
    name: "Trophy",
    category: "sports",
    url: "/clipart/sports/trophy.svg",
    tags: ["trophy", "winner", "champion", "cup"],
  },
  {
    id: "sport-trophy-arrow",
    name: "Victory Arrow",
    category: "sports",
    url: "/clipart/sports/trophy-arrow.svg",
    tags: ["arrow", "victory", "up", "achievement"],
  },
  {
    id: "sport-medal",
    name: "Medal",
    category: "sports",
    url: "/clipart/sports/medal.svg",
    tags: ["medal", "reward", "winner", "award"],
  },
  {
    id: "sport-champion",
    name: "Champion Star",
    category: "sports",
    url: "/clipart/sports/champion-star.svg",
    tags: ["champion", "star", "winner", "circle"],
  },

  /* Nature & Outdoors */
  {
    id: "nature-tree",
    name: "Pine Tree",
    category: "nature",
    url: "/clipart/nature/tree.svg",
    tags: ["tree", "pine", "forest", "nature"],
  },
  {
    id: "nature-mountains",
    name: "Mountains",
    category: "nature",
    url: "/clipart/nature/mountains.svg",
    tags: ["mountain", "adventure", "outdoor", "hiking"],
  },
  {
    id: "nature-plant",
    name: "Plant",
    category: "nature",
    url: "/clipart/nature/plant.svg",
    tags: ["plant", "leaf", "garden", "green"],
  },
  {
    id: "nature-sun",
    name: "Sun",
    category: "nature",
    url: "/clipart/nature/sun.svg",
    tags: ["sun", "sunshine", "summer", "bright"],
  },

  /* Love & Hearts */
  {
    id: "love-heart-solid",
    name: "Heart (Solid)",
    category: "love",
    url: "/clipart/love/heart-solid.svg",
    tags: ["heart", "love", "solid", "valentine"],
  },
  {
    id: "love-heart-outline",
    name: "Heart (Outline)",
    category: "love",
    url: "/clipart/love/heart-outline.svg",
    tags: ["heart", "love", "outline", "valentine"],
  },
  {
    id: "love-heart-check",
    name: "Heart Check",
    category: "love",
    url: "/clipart/love/heart-check.svg",
    tags: ["heart", "check", "approved", "love"],
  },
  {
    id: "love-ampersand",
    name: "Ampersand",
    category: "love",
    url: "/clipart/love/ampersand.svg",
    tags: ["and", "ampersand", "couple", "together"],
  },

  /* Icons & Symbols */
  {
    id: "icon-star",
    name: "Star (Solid)",
    category: "icons",
    url: "/clipart/icons/star.svg",
    tags: ["star", "rating", "favorite"],
  },
  {
    id: "icon-star-outline",
    name: "Star (Outline)",
    category: "icons",
    url: "/clipart/icons/star-outline.svg",
    tags: ["star", "outline", "rating"],
  },
  {
    id: "icon-warning",
    name: "Warning",
    category: "icons",
    url: "/clipart/icons/warning.svg",
    tags: ["warning", "alert", "caution", "danger"],
  },
  {
    id: "icon-speech",
    name: "Speech Bubble",
    category: "icons",
    url: "/clipart/icons/speech-bubble.svg",
    tags: ["speech", "bubble", "talk", "chat"],
  },
  {
    id: "icon-thought",
    name: "Thought Bubble",
    category: "icons",
    url: "/clipart/icons/thought-bubble.svg",
    tags: ["thought", "bubble", "think", "idea"],
  },
  {
    id: "icon-check",
    name: "Checkmark",
    category: "icons",
    url: "/clipart/icons/checkmark-circle.svg",
    tags: ["check", "approved", "done", "ok"],
  },
  {
    id: "icon-arrow",
    name: "Arrow Up",
    category: "icons",
    url: "/clipart/icons/arrow-up.svg",
    tags: ["arrow", "up", "direction", "pointer"],
  },

  /* Borders & Dividers */
  {
    id: "deco-divider-dot",
    name: "Dot Divider",
    category: "decorative",
    url: "/clipart/decorative/divider-dot.svg",
    tags: ["divider", "line", "dot", "separator"],
  },
  {
    id: "deco-divider-diamond",
    name: "Diamond Divider",
    category: "decorative",
    url: "/clipart/decorative/divider-diamond.svg",
    tags: ["divider", "diamond", "separator"],
  },
  {
    id: "deco-wave",
    name: "Wave Line",
    category: "decorative",
    url: "/clipart/decorative/wave-line.svg",
    tags: ["wave", "curve", "decorative", "line"],
  },
  {
    id: "deco-waves",
    name: "Waves Pattern",
    category: "decorative",
    url: "/clipart/decorative/waves-pattern.svg",
    tags: ["waves", "pattern", "abstract", "decorative"],
  },
  {
    id: "deco-zigzag",
    name: "Zigzag",
    category: "decorative",
    url: "/clipart/decorative/zigzag.svg",
    tags: ["zigzag", "pattern", "border", "decorative"],
  },

  /* Music & Arts */
  {
    id: "music-note",
    name: "Music Note",
    category: "music",
    url: "/clipart/music/music-note.svg",
    tags: ["music", "note", "melody", "sound"],
  },
  {
    id: "music-vinyl",
    name: "Vinyl Record",
    category: "music",
    url: "/clipart/music/vinyl-record.svg",
    tags: ["vinyl", "record", "retro", "music"],
  },
  {
    id: "music-mic",
    name: "Microphone",
    category: "music",
    url: "/clipart/music/microphone.svg",
    tags: ["microphone", "sing", "karaoke", "voice"],
  },

  /* Food & Kitchen */
  {
    id: "food-chef-hat",
    name: "Chef Hat",
    category: "food",
    url: "/clipart/food/chef-hat.svg",
    tags: ["chef", "hat", "cooking", "kitchen"],
  },
  {
    id: "food-utensils",
    name: "Utensils",
    category: "food",
    url: "/clipart/food/utensils.svg",
    tags: ["fork", "knife", "utensils", "dining"],
  },
  {
    id: "food-coffee",
    name: "Coffee Cup",
    category: "food",
    url: "/clipart/food/coffee-cup.svg",
    tags: ["coffee", "cup", "drink", "cafe"],
  },

  /* Text Frames */
  {
    id: "typo-textbox",
    name: "Text Box",
    category: "typography",
    url: "/clipart/typography/text-box.svg",
    tags: ["text", "box", "frame", "label"],
  },
  {
    id: "typo-pill",
    name: "Pill Shape",
    category: "typography",
    url: "/clipart/typography/pill-shape.svg",
    tags: ["pill", "capsule", "rounded", "tag"],
  },
  {
    id: "typo-banner",
    name: "Banner Top",
    category: "typography",
    url: "/clipart/typography/banner-top.svg",
    tags: ["banner", "header", "top", "frame"],
  },
  {
    id: "typo-ribbon",
    name: "Ribbon Banner",
    category: "typography",
    url: "/clipart/typography/ribbon-banner.svg",
    tags: ["ribbon", "banner", "award", "label"],
  },
];

/* ─── Design colour palette ─── */
export const designerColorPalette = [
  "#000000",
  "#1A1A1A",
  "#374151",
  "#6B7280",
  "#9CA3AF",
  "#D1D5DB",
  "#F3F4F6",
  "#FFFFFF",
  "#991B1B",
  "#DC2626",
  "#EF4444",
  "#F87171",
  "#92400E",
  "#D97706",
  "#F59E0B",
  "#FBBF24",
  "#166534",
  "#16A34A",
  "#22C55E",
  "#4ADE80",
  "#1E3A5F",
  "#1D4ED8",
  "#3B82F6",
  "#60A5FA",
  "#581C87",
  "#7C3AED",
  "#8B5CF6",
  "#A78BFA",
  "#831843",
  "#DB2777",
  "#EC4899",
  "#F472B6",
  "#a7cf45",
  "#8ab52e",
  "#D4A853",
  "#E8C97A",
];

/* ─── Canvas defaults ─── */
export const canvasDefaults = {
  width: 600,
  height: 600,
  backgroundColor: "transparent",
  selectionColor: "rgba(27, 77, 62, 0.15)",
  selectionBorderColor: "#a7cf45",
  selectionLineWidth: 1,
  cornerColor: "#a7cf45",
  cornerStyle: "circle" as const,
  cornerSize: 10,
  transparentCorners: false,
  borderColor: "#a7cf45",
  borderScaleFactor: 1.5,
};

/* ─── Max file upload size (5 MB) ─── */
export const MAX_UPLOAD_SIZE_BYTES = 5 * 1024 * 1024;
export const ALLOWED_IMAGE_TYPES = [
  "image/jpeg",
  "image/png",
  "image/svg+xml",
  "image/webp",
];

/* ─── Design Template Categories ─── */
export const designTemplateCategories: DesignTemplateCategory[] = [
  { id: "all", name: "All Templates", emoji: "✨" },
  { id: "business", name: "Business & Corporate", emoji: "💼" },
  { id: "birthday", name: "Birthday & Party", emoji: "🎂" },
  { id: "sports", name: "Sports & Fitness", emoji: "⚽" },
  { id: "motivational", name: "Motivational", emoji: "💪" },
  { id: "nature", name: "Nature & Outdoors", emoji: "🌿" },
  { id: "music", name: "Music & Art", emoji: "🎵" },
  { id: "love", name: "Love & Family", emoji: "❤️" },
  { id: "funny", name: "Funny & Quirky", emoji: "😂" },
  { id: "seasonal", name: "Seasonal & Holiday", emoji: "🎄" },
  { id: "minimal", name: "Minimal & Clean", emoji: "◻️" },
];

/* ─── Pre-made Design Templates ─── */
export const designTemplates: DesignTemplate[] = [
  /* ── Business & Corporate ── */
  {
    id: "biz-badge-logo",
    name: "Badge Logo Tee",
    category: "business",
    productTypes: ["t-shirt", "hoodie", "sweatshirt"],
    emoji: "🏢",
    description: "Professional badge-style company branding",
    tags: ["corporate", "logo", "branding", "professional", "badge"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/badges/circle-badge.svg",
          left: 300,
          top: 200,
          scaleX: 1.2,
          scaleY: 1.2,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 200,
          width: 160,
          text: "YOUR\nLOGO",
          fontSize: 32,
          fontFamily: "Playfair Display",
          fontWeight: "bold",
          fill: "#3D6B1E",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 370,
          width: 400,
          text: "COMPANY NAME",
          fontSize: 34,
          fontFamily: "Inter",
          fontWeight: "bold",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 420,
          width: 400,
          text: "Your tagline goes here",
          fontSize: 14,
          fontFamily: "Inter",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
          fontStyle: "italic",
        },
      ],
    },
  },
  {
    id: "biz-team-trophy",
    name: "Team Event Shirt",
    category: "business",
    productTypes: ["t-shirt", "hoodie", "sweatshirt"],
    emoji: "🤝",
    description: "Team building or corporate event design with trophy",
    tags: ["team", "event", "corporate", "group", "trophy"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "textbox",
          left: 300,
          top: 120,
          width: 500,
          text: "TEAM BUILDING",
          fontSize: 38,
          fontFamily: "Inter",
          fontWeight: "900",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 200,
        },
        {
          type: "textbox",
          left: 300,
          top: 165,
          width: 500,
          text: "2025",
          fontSize: 52,
          fontFamily: "Playfair Display",
          fontWeight: "bold",
          fill: "#3D6B1E",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
        {
          type: "image",
          src: "/clipart/sports/trophy.svg",
          left: 300,
          top: 300,
          scaleX: 1.5,
          scaleY: 1.5,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 450,
          width: 400,
          text: "Company Name Here",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "600",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },
  {
    id: "biz-hexagon-brand",
    name: "Hex Brand Tee",
    category: "business",
    productTypes: ["t-shirt", "hoodie", "sweatshirt", "cap"],
    emoji: "⬡",
    description: "Modern hexagon badge branding design",
    tags: ["corporate", "modern", "hexagon", "badge", "brand"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/badges/hexagon-badge.svg",
          left: 300,
          top: 230,
          scaleX: 1.6,
          scaleY: 1.6,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 210,
          width: 120,
          text: "YOUR",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "bold",
          fill: "#3D6B1E",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 300,
        },
        {
          type: "textbox",
          left: 300,
          top: 245,
          width: 120,
          text: "BRAND",
          fontSize: 24,
          fontFamily: "Playfair Display",
          fontWeight: "bold",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 420,
          width: 400,
          text: "EST. 2025",
          fontSize: 14,
          fontFamily: "Inter",
          fill: "#9CA3AF",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 400,
        },
      ],
    },
  },

  /* ── Sports & Fitness ── */
  {
    id: "sport-champion",
    name: "Champion Tee",
    category: "sports",
    productTypes: ["t-shirt", "hoodie", "sweatshirt"],
    emoji: "🏆",
    description: "Championship medal design for sports teams",
    tags: ["champion", "medal", "sports", "winner", "team"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/sports/medal.svg",
          left: 300,
          top: 180,
          scaleX: 1.3,
          scaleY: 1.3,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 330,
          width: 500,
          text: "CHAMPIONS",
          fontSize: 46,
          fontFamily: "Inter",
          fontWeight: "900",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 200,
        },
        {
          type: "image",
          src: "/clipart/decorative/divider-diamond.svg",
          left: 300,
          top: 370,
          scaleX: 1.2,
          scaleY: 1.2,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 420,
          width: 400,
          text: "LEAGUE 2025",
          fontSize: 16,
          fontFamily: "Inter",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 300,
        },
      ],
    },
  },
  {
    id: "sport-football-star",
    name: "Football Star",
    category: "sports",
    productTypes: ["t-shirt", "hoodie", "sweatshirt"],
    emoji: "⚽",
    description: "Football-themed design with star badge",
    tags: ["football", "soccer", "star", "team", "jersey"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/sports/champion-star.svg",
          left: 300,
          top: 160,
          scaleX: 1.4,
          scaleY: 1.4,
          originX: "center",
          originY: "center",
        },
        {
          type: "image",
          src: "/clipart/sports/football.svg",
          left: 300,
          top: 300,
          scaleX: 1.0,
          scaleY: 1.0,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 430,
          width: 500,
          text: "FOOTBALL CLUB",
          fontSize: 32,
          fontFamily: "Inter",
          fontWeight: "900",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 150,
        },
        {
          type: "textbox",
          left: 300,
          top: 475,
          width: 400,
          text: "Est. 2025 · City Name",
          fontSize: 13,
          fontFamily: "Inter",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },
  {
    id: "sport-trophy-arrow",
    name: "Rising Champion",
    category: "sports",
    productTypes: ["t-shirt", "hoodie"],
    emoji: "🏅",
    description: "Trophy with upward arrow — growth & winning",
    tags: ["trophy", "winner", "growth", "rising", "motivation"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/sports/trophy-arrow.svg",
          left: 300,
          top: 240,
          scaleX: 1.5,
          scaleY: 1.5,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 420,
          width: 500,
          text: "RISE TO THE TOP",
          fontSize: 28,
          fontFamily: "Inter",
          fontWeight: "900",
          fill: "#3D6B1E",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 100,
        },
        {
          type: "textbox",
          left: 300,
          top: 460,
          width: 400,
          text: "Your Team · Season 2025",
          fontSize: 13,
          fontFamily: "Inter",
          fill: "#9CA3AF",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },

  /* ── Birthday & Celebration ── */
  {
    id: "bday-star-badge",
    name: "Birthday Star",
    category: "birthday",
    productTypes: ["t-shirt", "hoodie", "sweatshirt", "mug"],
    emoji: "🎂",
    description: "Star badge birthday celebration design",
    tags: ["birthday", "party", "star", "celebration", "age"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/badges/star-badge.svg",
          left: 300,
          top: 200,
          scaleX: 1.5,
          scaleY: 1.5,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 195,
          width: 100,
          text: "30",
          fontSize: 56,
          fontFamily: "Playfair Display",
          fontWeight: "bold",
          fill: "#3D6B1E",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 350,
          width: 400,
          text: "HAPPY BIRTHDAY",
          fontSize: 30,
          fontFamily: "Inter",
          fontWeight: "900",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 200,
        },
        {
          type: "image",
          src: "/clipart/decorative/divider-dot.svg",
          left: 300,
          top: 390,
          scaleX: 1.0,
          scaleY: 1.0,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 430,
          width: 400,
          text: "Name · Date",
          fontSize: 14,
          fontFamily: "Inter",
          fill: "#9CA3AF",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },
  {
    id: "bday-oval-party",
    name: "Party Badge",
    category: "birthday",
    productTypes: ["t-shirt", "mug", "tote-bag"],
    emoji: "🎉",
    description: "Oval badge party celebration style",
    tags: ["birthday", "party", "badge", "celebration", "fun"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/badges/oval-badge.svg",
          left: 300,
          top: 250,
          scaleX: 1.5,
          scaleY: 1.5,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 220,
          width: 200,
          text: "LET'S",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "bold",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 300,
        },
        {
          type: "textbox",
          left: 300,
          top: 260,
          width: 200,
          text: "PARTY",
          fontSize: 36,
          fontFamily: "Playfair Display",
          fontWeight: "bold",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 430,
          width: 400,
          text: "Join us for a celebration! 🎈",
          fontSize: 14,
          fontFamily: "Inter",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },

  /* ── Nature & Outdoors ── */
  {
    id: "nature-mountain",
    name: "Mountain Explorer",
    category: "nature",
    productTypes: ["t-shirt", "hoodie", "sweatshirt", "tote-bag"],
    emoji: "🏔️",
    description: "Adventure-themed mountain landscape design",
    tags: ["mountain", "adventure", "outdoors", "hiking", "nature"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/nature/mountains.svg",
          left: 300,
          top: 200,
          scaleX: 1.5,
          scaleY: 1.5,
          originX: "center",
          originY: "center",
        },
        {
          type: "image",
          src: "/clipart/nature/sun.svg",
          left: 420,
          top: 130,
          scaleX: 0.5,
          scaleY: 0.5,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 360,
          width: 500,
          text: "EXPLORE MORE",
          fontSize: 36,
          fontFamily: "Inter",
          fontWeight: "900",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 150,
        },
        {
          type: "image",
          src: "/clipart/decorative/wave-line.svg",
          left: 300,
          top: 400,
          scaleX: 1.0,
          scaleY: 1.0,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 440,
          width: 400,
          text: "The adventure begins here",
          fontSize: 14,
          fontFamily: "Inter",
          fontStyle: "italic",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },
  {
    id: "nature-tree-life",
    name: "Tree of Life",
    category: "nature",
    productTypes: ["t-shirt", "tote-bag", "hoodie"],
    emoji: "🌳",
    description: "Peaceful tree design with nature theme",
    tags: ["tree", "nature", "life", "peace", "green", "eco"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/nature/tree.svg",
          left: 300,
          top: 220,
          scaleX: 1.5,
          scaleY: 1.5,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 400,
          width: 400,
          text: "STAY ROOTED",
          fontSize: 28,
          fontFamily: "Playfair Display",
          fontWeight: "bold",
          fill: "#3D6B1E",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 445,
          width: 400,
          text: "grow with purpose",
          fontSize: 14,
          fontFamily: "Inter",
          fontStyle: "italic",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },
  {
    id: "nature-plant-lover",
    name: "Plant Parent",
    category: "nature",
    productTypes: ["t-shirt", "mug", "tote-bag", "apron"],
    emoji: "🌱",
    description: "Cute plant lover design",
    tags: ["plant", "garden", "green", "eco", "cute"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/nature/plant.svg",
          left: 300,
          top: 220,
          scaleX: 1.4,
          scaleY: 1.4,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 380,
          width: 400,
          text: "PLANT PARENT",
          fontSize: 30,
          fontFamily: "Inter",
          fontWeight: "900",
          fill: "#3D6B1E",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 100,
        },
        {
          type: "image",
          src: "/clipart/decorative/divider-dot.svg",
          left: 300,
          top: 415,
          scaleX: 0.8,
          scaleY: 0.8,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 450,
          width: 400,
          text: "Growing things with love 🌿",
          fontSize: 13,
          fontFamily: "Inter",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },

  /* ── Love & Family ── */
  {
    id: "love-heart-badge",
    name: "Love Badge",
    category: "love",
    productTypes: ["t-shirt", "hoodie", "mug", "tote-bag"],
    emoji: "❤️",
    description: "Heart badge design for couples or family",
    tags: ["love", "heart", "couple", "family", "romance"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/love/heart-solid.svg",
          left: 300,
          top: 200,
          scaleX: 1.5,
          scaleY: 1.5,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 350,
          width: 400,
          text: "LOVE",
          fontSize: 48,
          fontFamily: "Playfair Display",
          fontWeight: "bold",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 410,
          width: 400,
          text: "Name & Name · Since 2025",
          fontSize: 14,
          fontFamily: "Inter",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },
  {
    id: "love-ampersand",
    name: "You & Me",
    category: "love",
    productTypes: ["t-shirt", "mug", "hoodie", "pillowcase"],
    emoji: "💕",
    description: "Elegant ampersand couples design",
    tags: ["love", "couple", "ampersand", "wedding", "anniversary"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "textbox",
          left: 300,
          top: 140,
          width: 300,
          text: "Name",
          fontSize: 32,
          fontFamily: "Playfair Display",
          fontWeight: "bold",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
        {
          type: "image",
          src: "/clipart/love/ampersand.svg",
          left: 300,
          top: 250,
          scaleX: 1.2,
          scaleY: 1.2,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 360,
          width: 300,
          text: "Name",
          fontSize: 32,
          fontFamily: "Playfair Display",
          fontWeight: "bold",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
        {
          type: "image",
          src: "/clipart/decorative/divider-diamond.svg",
          left: 300,
          top: 420,
          scaleX: 0.8,
          scaleY: 0.8,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 460,
          width: 400,
          text: "Together Since 2025",
          fontSize: 14,
          fontFamily: "Inter",
          fill: "#9CA3AF",
          textAlign: "center",
          originX: "center",
          originY: "center",
          fontStyle: "italic",
        },
      ],
    },
  },

  /* ── Music & Art ── */
  {
    id: "music-vinyl-love",
    name: "Vinyl Vibes",
    category: "music",
    productTypes: ["t-shirt", "hoodie", "tote-bag"],
    emoji: "🎵",
    description: "Retro vinyl record music lover design",
    tags: ["music", "vinyl", "record", "retro", "vintage"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/music/vinyl-record.svg",
          left: 300,
          top: 220,
          scaleX: 1.5,
          scaleY: 1.5,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 390,
          width: 500,
          text: "VINYL VIBES",
          fontSize: 34,
          fontFamily: "Inter",
          fontWeight: "900",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 150,
        },
        {
          type: "textbox",
          left: 300,
          top: 435,
          width: 400,
          text: "good music never dies",
          fontSize: 14,
          fontFamily: "Inter",
          fontStyle: "italic",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },
  {
    id: "music-mic-star",
    name: "Stage Star",
    category: "music",
    productTypes: ["t-shirt", "hoodie"],
    emoji: "🎤",
    description: "Microphone and star design for performers",
    tags: ["music", "microphone", "singer", "performer", "star", "stage"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/icons/star.svg",
          left: 300,
          top: 130,
          scaleX: 0.7,
          scaleY: 0.7,
          originX: "center",
          originY: "center",
        },
        {
          type: "image",
          src: "/clipart/music/microphone.svg",
          left: 300,
          top: 270,
          scaleX: 1.5,
          scaleY: 1.5,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 425,
          width: 500,
          text: "BORN TO PERFORM",
          fontSize: 28,
          fontFamily: "Inter",
          fontWeight: "900",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 100,
        },
        {
          type: "textbox",
          left: 300,
          top: 465,
          width: 400,
          text: "Your Name Here",
          fontSize: 14,
          fontFamily: "Inter",
          fill: "#9CA3AF",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },

  /* ── Motivational ── */
  {
    id: "moti-check-goals",
    name: "Goal Crusher",
    category: "motivational",
    productTypes: ["t-shirt", "hoodie", "sweatshirt", "mug"],
    emoji: "💪",
    description: "Checkmark achievement motivational design",
    tags: ["motivational", "goals", "achieve", "success", "check"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/icons/checkmark-circle.svg",
          left: 300,
          top: 180,
          scaleX: 1.4,
          scaleY: 1.4,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 330,
          width: 500,
          text: "CRUSH YOUR\nGOALS",
          fontSize: 38,
          fontFamily: "Inter",
          fontWeight: "900",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
        {
          type: "image",
          src: "/clipart/decorative/zigzag.svg",
          left: 300,
          top: 420,
          scaleX: 1.0,
          scaleY: 1.0,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 460,
          width: 400,
          text: "No excuses. Just results.",
          fontSize: 13,
          fontFamily: "Inter",
          fontStyle: "italic",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },
  {
    id: "moti-arrow-up",
    name: "Level Up",
    category: "motivational",
    productTypes: ["t-shirt", "hoodie", "sweatshirt"],
    emoji: "⬆️",
    description: "Upward arrow motivational growth design",
    tags: ["motivational", "growth", "up", "arrow", "level"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/icons/arrow-up.svg",
          left: 300,
          top: 180,
          scaleX: 1.5,
          scaleY: 1.5,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 340,
          width: 500,
          text: "LEVEL UP",
          fontSize: 48,
          fontFamily: "Inter",
          fontWeight: "900",
          fill: "#3D6B1E",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 200,
        },
        {
          type: "textbox",
          left: 300,
          top: 400,
          width: 400,
          text: "Every day is a new opportunity",
          fontSize: 14,
          fontFamily: "Inter",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
          fontStyle: "italic",
        },
      ],
    },
  },

  /* ── Food & Drink ── */
  {
    id: "food-chef-life",
    name: "Chef Life",
    category: "funny",
    productTypes: ["t-shirt", "apron", "mug"],
    emoji: "👨‍🍳",
    description: "Chef hat design for cooking enthusiasts",
    tags: ["chef", "cooking", "kitchen", "food", "apron"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/food/chef-hat.svg",
          left: 300,
          top: 180,
          scaleX: 1.4,
          scaleY: 1.4,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 330,
          width: 500,
          text: "CHEF LIFE",
          fontSize: 38,
          fontFamily: "Playfair Display",
          fontWeight: "bold",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
        {
          type: "image",
          src: "/clipart/food/utensils.svg",
          left: 300,
          top: 400,
          scaleX: 0.8,
          scaleY: 0.8,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 455,
          width: 400,
          text: "kiss the cook",
          fontSize: 14,
          fontFamily: "Inter",
          fontStyle: "italic",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },
  {
    id: "food-coffee-mug",
    name: "Coffee Lover",
    category: "funny",
    productTypes: ["mug", "t-shirt", "tote-bag"],
    emoji: "☕",
    description: "Coffee cup design for caffeine enthusiasts",
    tags: ["coffee", "mug", "morning", "caffeine", "drink"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/food/coffee-cup.svg",
          left: 300,
          top: 210,
          scaleX: 1.5,
          scaleY: 1.5,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 370,
          width: 400,
          text: "BUT FIRST,\nCOFFEE",
          fontSize: 32,
          fontFamily: "Inter",
          fontWeight: "900",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 450,
          width: 400,
          text: "fuelled by caffeine ☕",
          fontSize: 13,
          fontFamily: "Inter",
          fill: "#9CA3AF",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },

  /* ── Minimal & Clean ── */
  {
    id: "minimal-monogram",
    name: "Monogram Circle",
    category: "minimal",
    productTypes: ["t-shirt", "hoodie", "cap", "tote-bag", "mug"],
    emoji: "◻️",
    description: "Clean monogram inside a circle badge",
    tags: ["minimal", "monogram", "initials", "clean", "simple"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/badges/circle-badge.svg",
          left: 300,
          top: 260,
          scaleX: 1.4,
          scaleY: 1.4,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 260,
          width: 150,
          text: "AB",
          fontSize: 52,
          fontFamily: "Playfair Display",
          fontWeight: "bold",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },
  {
    id: "minimal-pill-tag",
    name: "Pill Tag",
    category: "minimal",
    productTypes: ["t-shirt", "hoodie", "cap", "tote-bag"],
    emoji: "💊",
    description: "Minimal pill-shaped label design",
    tags: ["minimal", "pill", "tag", "label", "clean"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/typography/pill-shape.svg",
          left: 300,
          top: 260,
          scaleX: 1.5,
          scaleY: 1.5,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 260,
          width: 200,
          text: "YOUR TEXT",
          fontSize: 18,
          fontFamily: "Inter",
          fontWeight: "bold",
          fill: "#FFFFFF",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 200,
        },
      ],
    },
  },
  {
    id: "minimal-ribbon",
    name: "Ribbon Banner",
    category: "minimal",
    productTypes: ["t-shirt", "hoodie", "mug", "tote-bag"],
    emoji: "🎀",
    description: "Classic ribbon banner with custom text",
    tags: ["minimal", "ribbon", "banner", "classic", "text"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/typography/ribbon-banner.svg",
          left: 300,
          top: 260,
          scaleX: 1.6,
          scaleY: 1.6,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 255,
          width: 200,
          text: "YOUR TEXT",
          fontSize: 16,
          fontFamily: "Inter",
          fontWeight: "bold",
          fill: "#FFFFFF",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 150,
        },
      ],
    },
  },

  /* ── Seasonal & Holiday ── */
  {
    id: "season-music-fest",
    name: "Music Festival",
    category: "seasonal",
    productTypes: ["t-shirt", "hoodie", "tote-bag"],
    emoji: "🎄",
    description: "Music festival / summer event design",
    tags: ["festival", "summer", "music", "event", "concert"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/music/music-note.svg",
          left: 180,
          top: 160,
          scaleX: 0.8,
          scaleY: 0.8,
          originX: "center",
          originY: "center",
        },
        {
          type: "image",
          src: "/clipart/music/music-note.svg",
          left: 420,
          top: 130,
          scaleX: 0.6,
          scaleY: 0.6,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 250,
          width: 500,
          text: "MUSIC\nFESTIVAL",
          fontSize: 44,
          fontFamily: "Inter",
          fontWeight: "900",
          fill: "#1A1A1A",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
        {
          type: "image",
          src: "/clipart/decorative/waves-pattern.svg",
          left: 300,
          top: 370,
          scaleX: 1.0,
          scaleY: 1.0,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 430,
          width: 400,
          text: "Summer 2025 · City Name",
          fontSize: 14,
          fontFamily: "Inter",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },
  {
    id: "season-nature-camp",
    name: "Summer Camp",
    category: "seasonal",
    productTypes: ["t-shirt", "hoodie", "cap"],
    emoji: "⛺",
    description: "Summer camp / outdoor event design",
    tags: ["summer", "camp", "outdoor", "nature", "adventure"],
    canvasJSON: {
      version: "6.0.0",
      objects: [
        {
          type: "image",
          src: "/clipart/nature/sun.svg",
          left: 300,
          top: 130,
          scaleX: 0.8,
          scaleY: 0.8,
          originX: "center",
          originY: "center",
        },
        {
          type: "image",
          src: "/clipart/nature/mountains.svg",
          left: 300,
          top: 240,
          scaleX: 1.3,
          scaleY: 1.3,
          originX: "center",
          originY: "center",
        },
        {
          type: "image",
          src: "/clipart/nature/tree.svg",
          left: 180,
          top: 280,
          scaleX: 0.6,
          scaleY: 0.6,
          originX: "center",
          originY: "center",
        },
        {
          type: "image",
          src: "/clipart/nature/tree.svg",
          left: 420,
          top: 280,
          scaleX: 0.6,
          scaleY: 0.6,
          originX: "center",
          originY: "center",
        },
        {
          type: "textbox",
          left: 300,
          top: 390,
          width: 500,
          text: "SUMMER CAMP",
          fontSize: 32,
          fontFamily: "Inter",
          fontWeight: "900",
          fill: "#3D6B1E",
          textAlign: "center",
          originX: "center",
          originY: "center",
          charSpacing: 200,
        },
        {
          type: "textbox",
          left: 300,
          top: 435,
          width: 400,
          text: "2025 · Adventure Awaits",
          fontSize: 14,
          fontFamily: "Inter",
          fill: "#6B7280",
          textAlign: "center",
          originX: "center",
          originY: "center",
        },
      ],
    },
  },
];
