import type {
  ProductTemplate,
  FontOption,
  ClipartCategory,
  ClipartItem,
  ProductColor,
} from "@/types/designer";

/* ─── Default Product Colors ─── */
export const defaultProductColors: ProductColor[] = [
  { name: "White", hex: "#FFFFFF" },
  { name: "Black", hex: "#1A1A1A" },
  { name: "Navy", hex: "#1B2A4A" },
  { name: "Brand Green", hex: "#a7cf45" },
  { name: "Red", hex: "#DC2626" },
  { name: "Royal Blue", hex: "#1D4ED8" },
  { name: "Grey", hex: "#6B7280" },
  { name: "Sand", hex: "#D4A853" },
];

/* ─── Product Templates ─── */
export const productTemplates: ProductTemplate[] = [
  {
    id: "tshirt-classic",
    type: "t-shirt",
    name: "Classic T-Shirt",
    description: "Unisex cotton crew-neck tee — perfect for custom prints",
    colors: defaultProductColors,
    views: [
      {
        id: "front",
        label: "Front",
        printArea: { top: 18, left: 25, width: 50, height: 45 },
        mockupImage: "/images/products/tshirt-front.png",
      },
      {
        id: "back",
        label: "Back",
        printArea: { top: 15, left: 25, width: 50, height: 50 },
        mockupImage: "/images/products/tshirt-back.png",
      },
    ],
    basePriceInPence: 1999,
    category: "Clothing",
    thumbnail: "/images/products/tshirt-thumb.png",
  },
  {
    id: "hoodie-pullover",
    type: "hoodie",
    name: "Pullover Hoodie",
    description: "Warm cotton-blend hoodie with front pouch pocket",
    colors: defaultProductColors,
    views: [
      {
        id: "front",
        label: "Front",
        printArea: { top: 22, left: 22, width: 56, height: 40 },
        mockupImage: "/images/products/hoodie-front.png",
      },
      {
        id: "back",
        label: "Back",
        printArea: { top: 15, left: 20, width: 60, height: 50 },
        mockupImage: "/images/products/hoodie-back.png",
      },
    ],
    basePriceInPence: 3999,
    category: "Clothing",
    thumbnail: "/images/products/hoodie-thumb.png",
  },
  {
    id: "sweatshirt-crew",
    type: "sweatshirt",
    name: "Crew Sweatshirt",
    description: "Classic crew-neck sweatshirt in heavyweight cotton",
    colors: defaultProductColors,
    views: [
      {
        id: "front",
        label: "Front",
        printArea: { top: 20, left: 22, width: 56, height: 42 },
        mockupImage: "/images/products/sweatshirt-front.png",
      },
      {
        id: "back",
        label: "Back",
        printArea: { top: 15, left: 20, width: 60, height: 48 },
        mockupImage: "/images/products/sweatshirt-back.png",
      },
    ],
    basePriceInPence: 3499,
    category: "Clothing",
    thumbnail: "/images/products/sweatshirt-thumb.png",
  },
  {
    id: "tote-bag-standard",
    type: "tote-bag",
    name: "Cotton Tote Bag",
    description: "Natural cotton tote — ideal for eco-friendly branding",
    colors: [
      { name: "Natural", hex: "#F5F0E8" },
      { name: "Black", hex: "#1A1A1A" },
      { name: "Navy", hex: "#1B2A4A" },
    ],
    views: [
      {
        id: "front",
        label: "Front",
        printArea: { top: 10, left: 15, width: 70, height: 65 },
        mockupImage: "/images/products/tote-front.png",
      },
    ],
    basePriceInPence: 1499,
    category: "Accessories",
    thumbnail: "/images/products/tote-thumb.png",
  },
  {
    id: "mug-ceramic",
    type: "mug",
    name: "Ceramic Mug (11oz)",
    description: "Classic white ceramic mug — dishwasher safe",
    colors: [{ name: "White", hex: "#FFFFFF" }],
    views: [
      {
        id: "front",
        label: "Wrap",
        printArea: { top: 15, left: 10, width: 80, height: 55 },
        mockupImage: "/images/products/mug-front.png",
      },
    ],
    basePriceInPence: 1299,
    category: "Drinkware",
    thumbnail: "/images/products/mug-thumb.png",
  },
  {
    id: "cap-snapback",
    type: "cap",
    name: "Snapback Cap",
    description: "Structured snapback with embroidery-ready front panel",
    colors: defaultProductColors.slice(0, 5),
    views: [
      {
        id: "front",
        label: "Front",
        printArea: { top: 10, left: 20, width: 60, height: 40 },
        mockupImage: "/images/products/cap-front.png",
      },
    ],
    basePriceInPence: 1699,
    category: "Accessories",
    thumbnail: "/images/products/cap-thumb.png",
  },
  {
    id: "apron-chef",
    type: "apron",
    name: "Chef's Apron",
    description: "Full-length apron with adjustable neck strap",
    colors: [
      { name: "Black", hex: "#1A1A1A" },
      { name: "White", hex: "#FFFFFF" },
      { name: "Navy", hex: "#1B2A4A" },
    ],
    views: [
      {
        id: "front",
        label: "Front",
        printArea: { top: 8, left: 20, width: 60, height: 50 },
        mockupImage: "/images/products/apron-front.png",
      },
    ],
    basePriceInPence: 1899,
    category: "Clothing",
    thumbnail: "/images/products/apron-thumb.png",
  },
  {
    id: "glass-can-16oz",
    type: "glass-can",
    name: "Glass Can (16oz)",
    description: "Trendy glass can tumbler with bamboo lid",
    colors: [{ name: "Clear", hex: "#E8F4F8" }],
    views: [
      {
        id: "front",
        label: "Wrap",
        printArea: { top: 10, left: 10, width: 80, height: 65 },
        mockupImage: "/images/products/glasscan-front.png",
      },
    ],
    basePriceInPence: 1599,
    category: "Drinkware",
    thumbnail: "/images/products/glasscan-thumb.png",
  },
  {
    id: "tumbler-20oz",
    type: "tumbler",
    name: "Insulated Tumbler (20oz)",
    description: "Stainless steel tumbler — keeps drinks hot or cold",
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#1A1A1A" },
      { name: "Gold", hex: "#D4A853" },
    ],
    views: [
      {
        id: "front",
        label: "Wrap",
        printArea: { top: 8, left: 10, width: 80, height: 70 },
        mockupImage: "/images/products/tumbler-front.png",
      },
    ],
    basePriceInPence: 1899,
    category: "Drinkware",
    thumbnail: "/images/products/tumbler-thumb.png",
  },
  {
    id: "pillowcase-square",
    type: "pillowcase",
    name: "Square Pillowcase",
    description: "Soft polyester pillowcase — vibrant sublimation print",
    colors: [{ name: "White", hex: "#FFFFFF" }],
    views: [
      {
        id: "front",
        label: "Front",
        printArea: { top: 5, left: 5, width: 90, height: 90 },
        mockupImage: "/images/products/pillowcase-front.png",
      },
    ],
    basePriceInPence: 1899,
    category: "Home & Living",
    thumbnail: "/images/products/pillowcase-thumb.png",
  },
];

/* ─── Font Library ─── */
export const designerFonts: FontOption[] = [
  { family: "Inter", category: "sans-serif" },
  { family: "Playfair Display", category: "serif" },
  { family: "Roboto", category: "sans-serif" },
  { family: "Open Sans", category: "sans-serif" },
  { family: "Montserrat", category: "sans-serif" },
  { family: "Lato", category: "sans-serif" },
  { family: "Poppins", category: "sans-serif" },
  { family: "Oswald", category: "sans-serif" },
  { family: "Raleway", category: "sans-serif" },
  { family: "Merriweather", category: "serif" },
  { family: "Lora", category: "serif" },
  { family: "PT Serif", category: "serif" },
  { family: "Bebas Neue", category: "display" },
  { family: "Lobster", category: "display" },
  { family: "Permanent Marker", category: "handwriting" },
  { family: "Pacifico", category: "handwriting" },
  { family: "Dancing Script", category: "handwriting" },
  { family: "Caveat", category: "handwriting" },
  { family: "Shadows Into Light", category: "handwriting" },
  { family: "Source Code Pro", category: "monospace" },
  { family: "Abril Fatface", category: "display" },
  { family: "Righteous", category: "display" },
  { family: "Bangers", category: "display" },
  { family: "Press Start 2P", category: "display" },
  { family: "Anton", category: "sans-serif" },
  { family: "Archivo Black", category: "sans-serif" },
  { family: "Titan One", category: "display" },
  { family: "Sacramento", category: "handwriting" },
  { family: "Great Vibes", category: "handwriting" },
  { family: "Satisfy", category: "handwriting" },
];

/* ─── Clipart Categories ─── */
export const clipartCategories: ClipartCategory[] = [
  { id: "business", name: "Business & Corporate", icon: "Briefcase" },
  { id: "sports", name: "Sports & Fitness", icon: "Trophy" },
  { id: "nature", name: "Nature & Animals", icon: "TreePine" },
  { id: "food", name: "Food & Drink", icon: "Coffee" },
  { id: "celebration", name: "Celebration & Events", icon: "PartyPopper" },
  { id: "shapes", name: "Shapes & Borders", icon: "Shapes" },
  { id: "arrows", name: "Arrows & Icons", icon: "ArrowRight" },
  { id: "love", name: "Love & Hearts", icon: "Heart" },
  { id: "music", name: "Music & Arts", icon: "Music" },
  { id: "travel", name: "Travel & Places", icon: "Plane" },
];

/* ─── Design colour palette ─── */
export const designerColorPalette = [
  "#000000",
  "#1A1A1A",
  "#374151",
  "#6B7280",
  "#9CA3AF",
  "#D1D5DB",
  "#F3F4F6",
  "#FFFFFF",
  "#991B1B",
  "#DC2626",
  "#EF4444",
  "#F87171",
  "#92400E",
  "#D97706",
  "#F59E0B",
  "#FBBF24",
  "#166534",
  "#16A34A",
  "#22C55E",
  "#4ADE80",
  "#1E3A5F",
  "#1D4ED8",
  "#3B82F6",
  "#60A5FA",
  "#581C87",
  "#7C3AED",
  "#8B5CF6",
  "#A78BFA",
  "#831843",
  "#DB2777",
  "#EC4899",
  "#F472B6",
  "#a7cf45",
  "#8ab52e",
  "#D4A853",
  "#E8C97A",
];

/* ─── Canvas defaults ─── */
export const canvasDefaults = {
  width: 600,
  height: 600,
  backgroundColor: "transparent",
  selectionColor: "rgba(27, 77, 62, 0.15)",
  selectionBorderColor: "#a7cf45",
  selectionLineWidth: 1,
  cornerColor: "#a7cf45",
  cornerStyle: "circle" as const,
  cornerSize: 10,
  transparentCorners: false,
  borderColor: "#a7cf45",
  borderScaleFactor: 1.5,
};

/* ─── Max file upload size (5 MB) ─── */
export const MAX_UPLOAD_SIZE_BYTES = 5 * 1024 * 1024;
export const ALLOWED_IMAGE_TYPES = [
  "image/jpeg",
  "image/png",
  "image/svg+xml",
  "image/webp",
];
